<?php

if (!defined('ABSPATH'))
    exit;
oxi_team_show_slider_user_capabilities();
$styledata = Array('id' => 6, 'style_name' => 'style_6', 'css' => 'team-category|| team-category-style |oxi-team-cat-style-1| team-category-position|center| category-fot-size|16| category-color|#ac00b8| category-bg-color |rgba(0, 76, 163, 1)| category-hover-color |#ffffff| category-hover-bg-color|rgba(172, 0, 184, 1)| category-font-family |Adamina| category-font-weight |600| category-font-style |normal| category-padding-top-bottom |10| category-padding-left-right|10| category-border |2| category-border-type|dotted solid double dashed| category-border-radius |5| category-margin-top |5| category-margin-bottom |5| category-margin-left |20| category-margin-right|20|oxilab-carousel|| oxilab-carousel-center-mode|false| oxilab-carousel-autoplay|true| oxilab-carousel-autoplay-time|2| oxilab-carousel-pagination|true| oxilab-carousel-pagination-position|bottom center| oxilab-carousel-pagination-color|rgba(110, 110, 110, 1)| oxilab-carousel-pagination-active-color |rgba(224, 0, 134, 1)| oxilab-carousel-body-width|10| oxilab-carousel-active-body-size|1.2| oxilab-carousel-active-body-padding-top |20| oxilab-carousel-navigation |true| oxilab-carousel-navigation-style |fa-angle-left| others-navigation-data |oxilab-carousel-navigation-size//50//oxilab-carousel-navigation-color//rgba(110, 110, 110, 1)//oxilab-carousel-navigation-active-color//rgba(186, 0, 199, 1)//oxilab-carousel-navigation-position-top-bottom//31//oxilab-carousel-navigation-position-left-right//0//oxilab-carousel-navigation-showing-type//:hover//oxilab-carousel-body-height//10//oxilab-carousel-active-body-padding-left//7//oxilab-carousel-pagination-border-radius//10//| || team-width |262| team-height |262| team-item |oxi-team-show-col-3| team-icon-position |oxi-team-center| image-link-opening || image-margin-top |10| image-margin-bottom |20| team-animation || team-animation-duration |2| team-box-shadow-color |rgba(217, 217, 217, 0.73)| team-box-shadow-length-horizontal |0| team-box-shadow-length-vertical |2| team-box-shadow-radius-blur |8| team-box-shadow-radius-spread |0| team-box-bg-color |rgba(255, 255, 255, 1)| name-general-padding-top-bottom |8| name-general-padding-left-right |6| name-font-size |18| name-color |#6b6b6b| heading-font-family |Open+Sans| name-font-weight |600| name-font-style |normal| name-margin-top |6| name-margin-bottom |0| position-font-size |14| position-color |#7a7a7a| position-font-family |Open+Sans| position-font-weight |300| position-font-style |normal| position-margin-top |2| position-margin-bottom |0| icon-font-size |14| icon-color |#ffffff| || icon-width |28| icon-distance |4| icon-radius |0| icon-hover-radius |0| icon-background-color |rgba(222, 222, 222, 0.35)| icon-padding-top-bottom |10| || team-top-border-radius |10| team-bottom-border-radius |0| icon-style |oxi-member-icons-style-3| team-padding-top-bottom |10| team-padding-left-right |10||||| team-border-color |#cfcfcf| team-custom-css ||');
$listdata = Array(
    Array('id' => 1, 'styleid' => 6, 'title' => '', 'files' => 'oxi-team-name {#}|{#}Abdur Razzak{#}|{#} oxi-team-designation {#}|{#}CEO &amp; Founder{#}|{#} oxi-team-profile-image {#}|{#}' . oxi_team_show_admin_image('1.jpg') . '{#}|{#}oxi-team-socail-First {#}|{#}fab fa-linkedin-in{#}|{#}oxi-team-socail-First-url {#}|{#}#{#}|{#}oxi-team-socail-Second {#}|{#}fab fa-google-plus-g{#}|{#}oxi-team-socail-Second-url {#}|{#}#{#}|{#}oxi-team-socail-Third {#}|{#}fab fa-wordpress{#}|{#}oxi-team-socail-Third-url {#}|{#}#{#}|{#}oxi-team-socail-Forth {#}|{#}fab fa-facebook-f{#}|{#}oxi-team-socail-Forth-url {#}|{#}#{#}|{#}oxilab-team-category {#}|{#}{#}|{#}', 'css' => ''),
    Array('id' => 2, 'styleid' => 6, 'title' => '', 'files' => 'oxi-team-name {#}|{#}Abdur Rahman{#}|{#} oxi-team-designation {#}|{#}UX Designer{#}|{#} oxi-team-profile-image {#}|{#}' . oxi_team_show_admin_image('2.jpg') . '{#}|{#}oxi-team-socail-First {#}|{#}fab fa-linkedin-in{#}|{#}oxi-team-socail-First-url {#}|{#}#{#}|{#}oxi-team-socail-Second {#}|{#}fab fa-google-plus-g{#}|{#}oxi-team-socail-Second-url {#}|{#}#{#}|{#}oxi-team-socail-Third {#}|{#}fab fa-wordpress{#}|{#}oxi-team-socail-Third-url {#}|{#}#{#}|{#}oxi-team-socail-Forth {#}|{#}fab fa-facebook-f{#}|{#}oxi-team-socail-Forth-url {#}|{#}#{#}|{#}oxilab-team-category {#}|{#}{#}|{#}', 'css' => ''),
    Array('id' => 3, 'styleid' => 6, 'title' => '', 'files' => 'oxi-team-name {#}|{#}Abdul Khalek{#}|{#} oxi-team-designation {#}|{#}Developer{#}|{#} oxi-team-profile-image {#}|{#}' . oxi_team_show_admin_image('3.jpg') . '{#}|{#}oxi-team-socail-First {#}|{#}fab fa-linkedin-in{#}|{#}oxi-team-socail-First-url {#}|{#}#{#}|{#}oxi-team-socail-Second {#}|{#}fab fa-google-plus-g{#}|{#}oxi-team-socail-Second-url {#}|{#}#{#}|{#}oxi-team-socail-Third {#}|{#}fab fa-wordpress{#}|{#}oxi-team-socail-Third-url {#}|{#}#{#}|{#}oxi-team-socail-Forth {#}|{#}fab fa-facebook-f{#}|{#}oxi-team-socail-Forth-url {#}|{#}#{#}|{#}oxilab-team-category {#}|{#}{#}|{#}', 'css' => ''),
);
echo '<input type="hidden" name="oxi-team-data-' . $styledata['id'] . '" id="oxi-team-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
oxilab_team_admin_style_layouts($styledata, $listdata);
