<?php

if (!defined('ABSPATH'))
    exit;
oxi_team_show_slider_user_capabilities();
$styledata = Array('id' => 1, 'style_name' => 'style_1', 'css' => 'team-category|| team-category-style |oxi-team-cat-style-1| team-category-position|center| category-fot-size|16| category-color|#ac00b8| category-bg-color |rgba(0, 76, 163, 1)| category-hover-color |#ffffff| category-hover-bg-color|rgba(172, 0, 184, 1)| category-font-family |Open+Sans| category-font-weight |300| category-font-style |normal| category-padding-top-bottom |10| category-padding-left-right|10| category-border |2| category-border-type|solid| category-border-radius |2| category-margin-top |5| category-margin-bottom |5| category-margin-left |20| category-margin-right|20|oxilab-carousel|| oxilab-carousel-center-mode|false| oxilab-carousel-autoplay|true| oxilab-carousel-autoplay-time|2| oxilab-carousel-pagination|true| oxilab-carousel-pagination-position|bottom center| oxilab-carousel-pagination-color|rgba(110, 110, 110, 1)| oxilab-carousel-pagination-active-color |rgba(224, 0, 134, 1)| oxilab-carousel-body-width|10| oxilab-carousel-active-body-size|1.2| oxilab-carousel-active-body-padding-top |20| oxilab-carousel-navigation |true| oxilab-carousel-navigation-style |fa-angle-left| others-navigation-data |oxilab-carousel-navigation-size//50//oxilab-carousel-navigation-color//rgba(110, 110, 110, 1)//oxilab-carousel-navigation-active-color//rgba(186, 0, 199, 1)//oxilab-carousel-navigation-position-top-bottom//31//oxilab-carousel-navigation-position-left-right//0//oxilab-carousel-navigation-showing-type////oxilab-carousel-body-height//10//oxilab-carousel-active-body-padding-left//7//oxilab-carousel-pagination-border-radius//10//| || team-width |262| team-height |262| team-item |oxi-team-show-col-3| team-icon-position |oxi-team-center| image-link-opening || image-margin-top |20| team-animation || team-animation-duration |2| team-box-shadow-color |rgba(217, 217, 217, 0.73)| team-box-shadow-length-horizontal |0| team-box-shadow-length-vertical |2| team-box-shadow-radius-blur |8| team-box-shadow-radius-spread |0| name-font-size |18| name-color |#545454| heading-font-family |Open+Sans| name-font-weight |600| name-font-style |normal| name-margin-top |15| name-padding-bottom |10| bottom-width |30| bottom-height |1| bottom-color |#00c29b| name-margin-bottom |5| position-font-size |14| position-color |#949494| position-font-family |Open+Sans| position-font-weight |300| position-font-style |normal| position-margin-bottom |15| icon-font-size |14| icon-color |#ffffff| icon-background-color |#595959| icon-width |36| icon-padding-top-bottom |8| icon-arrow |8| image-margin-bottom |10| team-box-bg-color |rgba(255, 255, 255, 1)| team-custom-css ||');
$listdata = Array(
    Array('id' => 1, 'styleid' => 1, 'title' => '', 'files' => 'oxi-team-name {#}|{#}Abdur Razzak{#}|{#} oxi-team-designation {#}|{#}CEO &amp; Founder{#}|{#} oxi-team-profile-image {#}|{#}' . oxi_team_show_admin_image('1.jpg') . '{#}|{#}oxi-team-socail-First {#}|{#}fab fa-linkedin-in{#}|{#}oxi-team-socail-First-url {#}|{#}#{#}|{#}oxi-team-socail-Second {#}|{#}fab fa-google-plus-g{#}|{#}oxi-team-socail-Second-url {#}|{#}#{#}|{#}oxi-team-socail-Third {#}|{#}fab fa-wordpress{#}|{#}oxi-team-socail-Third-url {#}|{#}#{#}|{#}oxi-team-socail-Forth {#}|{#}fab fa-facebook-f{#}|{#}oxi-team-socail-Forth-url {#}|{#}#{#}|{#}oxilab-team-category {#}|{#}{#}|{#}', 'css' => ''),
    Array('id' => 2, 'styleid' => 1, 'title' => '', 'files' => 'oxi-team-name {#}|{#}Abdur Rahman{#}|{#} oxi-team-designation {#}|{#}UX Designer{#}|{#} oxi-team-profile-image {#}|{#}' . oxi_team_show_admin_image('2.jpg') . '{#}|{#}oxi-team-socail-First {#}|{#}fab fa-linkedin-in{#}|{#}oxi-team-socail-First-url {#}|{#}#{#}|{#}oxi-team-socail-Second {#}|{#}fab fa-google-plus-g{#}|{#}oxi-team-socail-Second-url {#}|{#}#{#}|{#}oxi-team-socail-Third {#}|{#}fab fa-wordpress{#}|{#}oxi-team-socail-Third-url {#}|{#}#{#}|{#}oxi-team-socail-Forth {#}|{#}fab fa-facebook-f{#}|{#}oxi-team-socail-Forth-url {#}|{#}#{#}|{#}oxilab-team-category {#}|{#}{#}|{#}', 'css' => ''),
    Array('id' => 3, 'styleid' => 1, 'title' => '', 'files' => 'oxi-team-name {#}|{#}Abdul Khalek{#}|{#} oxi-team-designation {#}|{#}Developer{#}|{#} oxi-team-profile-image {#}|{#}' . oxi_team_show_admin_image('3.jpg') . '{#}|{#}oxi-team-socail-First {#}|{#}fab fa-linkedin-in{#}|{#}oxi-team-socail-First-url {#}|{#}#{#}|{#}oxi-team-socail-Second {#}|{#}fab fa-google-plus-g{#}|{#}oxi-team-socail-Second-url {#}|{#}#{#}|{#}oxi-team-socail-Third {#}|{#}fab fa-wordpress{#}|{#}oxi-team-socail-Third-url {#}|{#}#{#}|{#}oxi-team-socail-Forth {#}|{#}fab fa-facebook-f{#}|{#}oxi-team-socail-Forth-url {#}|{#}#{#}|{#}oxilab-team-category {#}|{#}{#}|{#}', 'css' => ''),
);
echo '<input type="hidden" name="oxi-team-data-' . $styledata['id'] . '" id="oxi-team-data-' . $styledata['id'] . '" value="' . $styledata['css'] . '">';
oxilab_team_admin_style_layouts($styledata, $listdata);
